#!/bin/bash
## debian method
sudo apt install -y nvidia-driver-full nvidia-open-kernel-dkms nvidia-vaapi-driver xserver-xorg-video-amdgpu mesa-utils vulkan-validationlayers vulkan-tools nvidia-vulkan-common mesa-vulkan-drivers firmware-nvidia-graphics --install-recommends

sudo systemctl disable nvidia-persistenced nvidia-powerd

# sudo reboot
