#!/bin/bash
echo "Installing gtk theme"
sudo apt install gnome-themes-standard gtk2-engines-murrine sassc
cd && git clone https://github.com/vinceliuice/Colloid-gtk-theme.git
cd Colloid-gtk-theme 
./install.sh -c dark -l  --tweaks gruvbox
cd && sudo rm -rf Colloid-gtk-theme

echo "Installing Icons"
sudo apt install -y papirus-icon-theme
cd && git clone https://github.com/xelser/gruvbox-papirus-folders 
cd gruvbox-papirus-folders
sudo cp -r src/* /usr/share/icons/Papirus/
sudo ./papirus-folders -C gruvbox-material-organge --theme Papirus-Dark
cd && sudo rm -rf gruvbox-papirus-folders

echo "Installing Cursors"
sudo apt install -y bibata-cursor-theme

